In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('loan_data.csv')
df 

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [3]:
del df['purpose']
del df['dti']
del df['inq.last.6mths']
del df['installment']
del df['days.with.cr.line']

In [4]:
df.columns = ['MeetsCreditPolicy?', 'InterestRate', 'LogAnnualIncome', 'FICOScore', 'RevolvingBalance', 'RevolvingLineUtilisationRate', 'No. of Overdue Payments', 'NoofDerogatoryPublicRecords', 'LoanFullyPaid?']

In [5]:
null_values = df.isnull().sum()
null_values # There are no null values!

MeetsCreditPolicy?              0
InterestRate                    0
LogAnnualIncome                 0
FICOScore                       0
RevolvingBalance                0
RevolvingLineUtilisationRate    0
No. of Overdue Payments         0
NoofDerogatoryPublicRecords     0
LoanFullyPaid?                  0
dtype: int64

In [6]:
df['MeetsCreditPolicy?'].unique()

array([1, 0])

In [7]:
df['LoanFullyPaid?'].unique()

array([0, 1])

In [8]:
df['MeetsCreditPolicy?'].unique()

array([1, 0])

In [9]:
df.columns = ['Meets Credit Policy?', 'Interest Rate (%)', 'Log Annual Income ($)', 'FICO Score', 'Revolving Balance ($)', 'Revolving Line Utilisation Rate', 'No. of Overdue Payments', 'No. of Derogatory Public Records', 'Loan Fully Paid?']

In [10]:
df['Interest Rate (%)'] *= 100 # Display actual percentage 

In [11]:
df = df.round({'Log Annual Income ($)': 2}) # To 2 decimal places

In [12]:
df.columns = ['Meets Credit Policy?', 'Interest Rate (%)', 'Log Annual Income ($)', 'FICO Score', 'Revolving Balance ($)', 'Revolving Line Utilisation Rate', 'No. of Overdue Payments', 'No. of Derogatory Public Records', 'Loan Fully Paid?']

In [13]:
df.columns = ['Meets Credit Policy?', 'Interest Rate (%)', 'Log Annual Income ($)', 'FICO Score', 'Revolving Balance ($)', 'Revolving Line Utilisation Rate', 'No. of Overdue Payments', 'No. of Derogatory Public Records', 'Loan Not Fully Paid']

In [14]:
df

Meets Credit Policy?  Interest Rate (%)  Log Annual Income ($)  \
0                        1              11.89                  11.35   
1                        1              10.71                  11.08   
2                        1              13.57                  10.37   
3                        1              10.08                  11.35   
4                        1              14.26                  11.30   
...                    ...                ...                    ...   
9573                     0              14.61                  12.18   
9574                     0              12.53                  11.14   
9575                     0              10.71                  10.60   
9576                     0              16.00                  10.82   
9577                     0              13.92                  11.26   

      FICO Score  Revolving Balance ($)  Revolving Line Utilisation Rate  \
0            737                  28854                             52.1   
1            707                  33623                             76.7   
2            682                   3511                             25.6   
3            712                  33667                             73.2   
4            667                   4740                             39.5   
...          ...                    ...                              ...   
9573         672                 215372                             82.1   
9574         722                    184                              1.1   
9575         687                  10036                             82.9   
9576         692                      0                              3.2   
9577         732                  37879                             57.0   

      No. of Overdue Payments  No. of Derogatory Public Records  \
0                           0                                 0   
1                           0                                 0   
2                           0                                 0   
3                           0                                 0   
4                           1                                 0   
...                       ...                               ...   
9573                        0                                 0   
9574                        0                                 0   
9575                        0                                 0   
9576                        0                                 0   
9577                        0                                 0   

      Loan Not Fully Paid  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
...                   ...  
9573                    1  
9574                    1  
9575                    1  
9576                    1  
9577                    1  

[9578 rows x 9 columns]

In [15]:
df.describe() # Statistics like mean average to be later used during visualisation

Meets Credit Policy?  Interest Rate (%)  Log Annual Income ($)  \
count           9578.000000        9578.000000            9578.000000   
mean               0.804970          12.264006              10.932345   
std                0.396245           2.684699               0.614834   
min                0.000000           6.000000               7.550000   
25%                1.000000          10.390000              10.560000   
50%                1.000000          12.210000              10.930000   
75%                1.000000          14.070000              11.290000   
max                1.000000          21.640000              14.530000   

        FICO Score  Revolving Balance ($)  Revolving Line Utilisation Rate  \
count  9578.000000           9.578000e+03                      9578.000000   
mean    710.846314           1.691396e+04                        46.799236   
std      37.970537           3.375619e+04                        29.014417   
min     612.000000           0.000000e+00                         0.000000   
25%     682.000000           3.187000e+03                        22.600000   
50%     707.000000           8.596000e+03                        46.300000   
75%     737.000000           1.824950e+04                        70.900000   
max     827.000000           1.207359e+06                       119.000000   

       No. of Overdue Payments  No. of Derogatory Public Records  \
count              9578.000000                       9578.000000   
mean                  0.163708                          0.062122   
std                   0.546215                          0.262126   
min                   0.000000                          0.000000   
25%                   0.000000                          0.000000   
50%                   0.000000                          0.000000   
75%                   0.000000                          0.000000   
max                  13.000000                          5.000000   

       Loan Not Fully Paid  
count          9578.000000  
mean              0.160054  
std               0.366676  
min               0.000000  
25%               0.000000  
50%               0.000000  
75%               0.000000  
max               1.000000

In [16]:
df

Meets Credit Policy?  Interest Rate (%)  Log Annual Income ($)  \
0                        1              11.89                  11.35   
1                        1              10.71                  11.08   
2                        1              13.57                  10.37   
3                        1              10.08                  11.35   
4                        1              14.26                  11.30   
...                    ...                ...                    ...   
9573                     0              14.61                  12.18   
9574                     0              12.53                  11.14   
9575                     0              10.71                  10.60   
9576                     0              16.00                  10.82   
9577                     0              13.92                  11.26   

      FICO Score  Revolving Balance ($)  Revolving Line Utilisation Rate  \
0            737                  28854                             52.1   
1            707                  33623                             76.7   
2            682                   3511                             25.6   
3            712                  33667                             73.2   
4            667                   4740                             39.5   
...          ...                    ...                              ...   
9573         672                 215372                             82.1   
9574         722                    184                              1.1   
9575         687                  10036                             82.9   
9576         692                      0                              3.2   
9577         732                  37879                             57.0   

      No. of Overdue Payments  No. of Derogatory Public Records  \
0                           0                                 0   
1                           0                                 0   
2                           0                                 0   
3                           0                                 0   
4                           1                                 0   
...                       ...                               ...   
9573                        0                                 0   
9574                        0                                 0   
9575                        0                                 0   
9576                        0                                 0   
9577                        0                                 0   

      Loan Not Fully Paid  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
...                   ...  
9573                    1  
9574                    1  
9575                    1  
9576                    1  
9577                    1  

[9578 rows x 9 columns]

In [18]:
df.to_csv('FinalLoanData.csv')